apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ray-monitor
  namespace: prometheus-system
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - ray-operator
      - ray-jobs
  podMetricsEndpoints:
    - port: metrics
      path: /
      interval: 2s
      scrapeTimeout: 1s
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
          action: replace
  selector:
    matchLabels:
      ray.io/is-ray-node: "yes"
