apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: straggler-test
  namespace: ray-jobs
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  # Test with simulated stragglers to see resilience differences
  # Worker 0 will be 5x slower every 10 steps
  # Compare SSGD (blocks all), ASGD (no blocking), SSP (partial blocking)
  entrypoint: python -u /app/main.py --mode ssgd --num-workers 4 --total-updates 3000 --num-samples 1000000 --noise 0.005 --dim 100 --lr 0.005 --batch 16384 --device cuda --hetero-straggler-every 10 --hetero-base 0.01 --hetero-jitter 0.005
  shutdownAfterJobFinishes: true
  ttlSecondsAfterFinished: 1800
  runtimeEnvYAML: |
    env_vars:
      PYTHONPATH: "/app"
      NCCL_DEBUG: "INFO"
      NCCL_DEBUG_SUBSYS: "INIT,COLL,P2P,NET"
      NCCL_IB_DISABLE: "1"
      NCCL_SOCKET_IFNAME: "eth0"
      TORCH_DISTRIBUTED_DEBUG: "INFO"
      RAY_PROFILING: "1"
  rayClusterSpec:
    rayVersion: "2.53.0"
    headGroupSpec:
      rayStartParams:
        dashboard-host: "0.0.0.0"
        metrics-export-port: "8080"
        num-gpus: "1"
      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                  - key: ray.io/cluster
                    operator: In
                    values:
                    - straggler-test
                topologyKey: kubernetes.io/hostname
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
          nodeSelector:
            karpenter.sh/nodepool: gpu
          containers:
            - name: ray-head
              image: 496105080108.dkr.ecr.us-east-2.amazonaws.com/ddp:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 52365
                  name: api
                - containerPort: 8080
                  name: metrics
              resources:
                limits:
                  cpu: "2"
                  memory: "8Gi"
                  nvidia.com/gpu: "1"
                requests:
                  cpu: "500m"
                  memory: "4Gi"
                  nvidia.com/gpu: "1"
    workerGroupSpecs:
      - replicas: 3
        minReplicas: 3
        maxReplicas: 3
        groupName: worker-group
        rayStartParams:
          metrics-export-port: "8080"
          num-gpus: "1"
        template:
          spec:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                    - key: ray.io/cluster
                      operator: In
                      values:
                      - straggler-test
                  topologyKey: kubernetes.io/hostname
            tolerations:
              - key: nvidia.com/gpu
                operator: Exists
                effect: NoSchedule
            nodeSelector:
              karpenter.sh/nodepool: gpu
            containers:
              - name: ray-worker
                image: 496105080108.dkr.ecr.us-east-2.amazonaws.com/ddp:latest
                imagePullPolicy: Always
                ports:
                  - containerPort: 6379
                    name: gcs-server
                  - containerPort: 8265
                    name: dashboard
                  - containerPort: 10001
                    name: client
                  - containerPort: 52365
                    name: api
                  - containerPort: 8080
                    name: metrics
                resources:
                  limits:
                    cpu: "2"
                    memory: "8Gi"
                    nvidia.com/gpu: "1"
                  requests:
                    cpu: "500m"
                    memory: "4Gi"
                    nvidia.com/gpu: "1"
